name: CI Pipeline

on: [push]

env:
  FAKE_SECRET_KEY: ${{ secrets.FAKE_SECRET_KEY }}
  EXPIRE_TIME_MINUTES: ${{ secrets.EXPIRE_TIME_MINUTES }}

jobs:
  install-deps-run-tests:
    name: Install Dependencies and Run Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      # Checkout the local repo, using the commit that triggered this workflow
      - uses: actions/checkout@v3

      # Establishes Python, with version(s) enumerated
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install poetry
        uses: abatilo/actions-poetry@v2

      # Install Workflow dependencies from Pipfile
      - name: Install dependencies
        run: poetry install

      # Run tests
      - name: Run Tests
        run: poetry run pytest -v
        